### PR TITLE
wire: Remove usage of `BaseEncoding`

### PR DESCRIPTION
**Pull request by SebastianElvis**
The original Jira ticket: https://babylon-chain.atlassian.net/browse/BPC-32

Currently bbld old codebase uses two serialization formats: `BaseEncoding` and `WitnessEncoding`.  As Babylon does not need to be backward-compatible, it would be in our interest to remove the old `BaseEncoding`.

This PR removes all usages of `BaseEncoding` except for the following two places that are deeply coupled:

1. https://github.com/babylonchain-io/bbld/blob/main/peer/peer.go#L2254. If changing `wire.BaseEncoding` to `wire.WitnessEncoding`, `TestPeerListeners` will fail (where `OnTx` and `OnTxData` will time out).
2. https://github.com/babylonchain-io/bbld/blob/main/btcutil/psbt/psbt.go#L225. If changing `msgTx.DeserializeNoWitness` to `msgTx.Deserialize`, then a number of tests in `psbt_test.go` will fail.

The first issue seems to depend on how `MsgTx` and `MsgTxData` are encoded/decoded. The second issue requires us to modify a lot of test vectors in https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#test-vectors accordingly. Do you think we should address these two issues within this PR or in a separate PR? @KonradStaniec

### CODE REVIEW

**Comment by KonradStaniec** [comment]
@SebastianElvis to be honest I think having all necessary changes in one pr would be better, as then:
1. When we merge pr with `squash and merge`, then in case something go wrong with encoding it will be much easier revert the change or identify this pr as culprit
2. When we will have have all modification in one pr it will be easier to asses how big this change really is.

**Comment by SebastianElvis** [comment]
OK then, I'm on it

**Comment by SebastianElvis** [comment]
I have removed everything related to `BaseEncoding`. Now the entire code only uses `Witness`. However, there are two minor issues:

1. `BenchmarkCalcSigHash` and `BenchmarkCalcWitnessSigHash` are omitted. The two benchmarks use a previously generated transaction `txscript/data/many_inputs_tx.hex` encoded in `BaseEncoding`.
2. `TxHash` in `msgtx.go` is still in the code, although `WitnessHash` exists. The difference is that `TxHash` hashes everything except for the witness data, while `WitnessHash` hashes everything.

For 2, I suggest keeping `TxHash` as the witness data is not on-chain and we need a tx hash for the on-chain tx. For 1, do we need to fix these it with a new `txscript/data/many_inputs_tx.hex` encoded in `WitnessEncoding`? @KonradStaniec

**Comment by SebastianElvis** [comment]
Closed given the switched technical approach.

**Pull request closed without merging**
